#!/usr/bin/env python3

import json
import redis
import logging
import traceback


# some functions
def pub_email(to, subject="", body=""):
    r.publish("email:send", json.dumps(dict(to=str(to), subject=str(subject), body=str(body))))

# logging setup
logging.basicConfig(format='%(asctime)s %(message)s')

# redis setup
r = redis.StrictRedis()
ps = r.pubsub()
ps.subscribe(["email:receive"])

# listen loop
for item in ps.listen():
    if item["type"] == "message":
        try:
            d_r = json.loads(item["data"].decode())
            # process echo request
            if d_r["subject"].strip().lower() == "echo":
                pub_email(to=d_r["email"], subject="echo reply")
        except Exception:
            logging.error(traceback.format_exc())
