#!/usr/bin/env python3

import datetime
import json
import redis
import logging
import traceback

# logging setup
logging.basicConfig(format='%(asctime)s %(message)s', level=logging.DEBUG)

# redis setup
r = redis.StrictRedis()
ps = r.pubsub()
ps.subscribe(["email:receive"])

for item in ps.listen():
    if item["type"] == "message":
        try:
            d_r = json.loads(item["data"].decode())
            # process echo request
            if d_r["subject"].strip().lower() == "echo":
                # publish echo to sender
                r.publish("email:send",
                          json.dumps(dict(to=d_r["email"], subject="echo reply",
                                          body="server time = %sZ" % datetime.datetime.utcnow().isoformat())))
        except Exception:
            logging.error(traceback.format_exc())
